"use client";

import React from "react";
import {
  Calendar,
  User,
  Building,
  Clock,
  LayoutTemplate,
  FileText,
  DollarSign,
  TrendingUp,
  CalendarCheck,
  Clock3,
  Star,
} from "lucide-react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
} from "recharts";

interface TopPDFTemplateProps {
  hotelName: string;
  hotelAddress: string;
  contactNumber: string;
  email: string;
  dateRange: string;
  department: string;
  roomType: string;
  generatedBy: string;
  generatedOn: string;
  reportType: string;
  summary: {
    totalRevenue: string;
    occupancyRate: number;
    totalBookings: number;
    avgLOS: string;
    guestSatisfaction: number;
  };
  revenueTrendData: any[];
  occupancyData: any[];
  bookingsOverviewData: any[];
}

export default function TopPDFTemplate({
  hotelName,
  hotelAddress,
  contactNumber,
  email,
  dateRange,
  department,
  roomType,
  generatedBy,
  generatedOn,
  reportType,
  summary,
  revenueTrendData,
  occupancyData,
  bookingsOverviewData,
}: TopPDFTemplateProps) {
  const COLORS = ["#10b981", "#3b82f6", "#8b5cf6", "#64748b"];

  return (
    <div
      id="pdf-top-template"
      className="bg-white text-slate-900 absolute top-0 left-[-9999px] flex flex-col font-sans"
      style={{ width: "1000px", padding: "40px" }}
    >
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-full flex items-center justify-center bg-gradient-to-br from-indigo-500 to-purple-600 shadow-md overflow-hidden relative">
             <div className="absolute inset-0 rounded-full border-4 border-white/20" style={{ clipPath: 'polygon(50% 50%, 100% 0, 100% 100%, 50% 100%)', backgroundColor: 'rgba(255,255,255,0.4)' }} />
          </div>
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-slate-900 uppercase">
              {hotelName}
            </h1>
            <p className="text-[11px] font-semibold tracking-wider text-blue-600 uppercase">
              Hotel Management
            </p>
          </div>
        </div>
        <div className="text-right">
          <h2 className="text-2xl font-bold tracking-tight text-slate-900 uppercase">
            Reports & Analytics
          </h2>
          <p className="text-[13px] font-medium text-blue-600">
            Performance Summary Report
          </p>
        </div>
      </div>

      <hr className="border-t border-slate-200 mb-6" />

      {/* Metadata Section */}
      <div className="flex justify-between mb-8">
        <div className="flex flex-col gap-5 flex-1">
          <div className="flex items-start gap-3">
            <Calendar className="w-5 h-5 text-slate-400 mt-0.5" />
            <div>
              <p className="text-[11px] font-medium text-slate-500 uppercase tracking-wider mb-0.5">Date Range</p>
              <p className="text-[13px] font-semibold text-slate-800">{dateRange}</p>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <Building className="w-5 h-5 text-slate-400 mt-0.5" />
            <div>
              <p className="text-[11px] font-medium text-slate-500 uppercase tracking-wider mb-0.5">Department</p>
              <p className="text-[13px] font-semibold text-slate-800">{department}</p>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <LayoutTemplate className="w-5 h-5 text-slate-400 mt-0.5" />
            <div>
              <p className="text-[11px] font-medium text-slate-500 uppercase tracking-wider mb-0.5">Room Type</p>
              <p className="text-[13px] font-semibold text-slate-800">{roomType}</p>
            </div>
          </div>
        </div>
        <div className="flex flex-col gap-5 flex-1">
          <div className="flex items-start gap-3">
            <User className="w-5 h-5 text-slate-400 mt-0.5" />
            <div>
              <p className="text-[11px] font-medium text-slate-500 uppercase tracking-wider mb-0.5">Report Generated By</p>
              <p className="text-[13px] font-semibold text-slate-800">{generatedBy}</p>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <Clock className="w-5 h-5 text-slate-400 mt-0.5" />
            <div>
              <p className="text-[11px] font-medium text-slate-500 uppercase tracking-wider mb-0.5">Generated On</p>
              <p className="text-[13px] font-semibold text-slate-800">{generatedOn}</p>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <FileText className="w-5 h-5 text-slate-400 mt-0.5" />
            <div>
              <p className="text-[11px] font-medium text-slate-500 uppercase tracking-wider mb-0.5">Report Type</p>
              <p className="text-[13px] font-semibold text-slate-800">{reportType}</p>
            </div>
          </div>
        </div>
      </div>

      <hr className="border-t border-slate-200 mb-8" />

      {/* Summary Metrics */}
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-4">
          <div className="w-1 h-4 bg-blue-600"></div>
          <h3 className="text-sm font-bold text-slate-800 tracking-wider uppercase">Summary Metrics</h3>
        </div>

        <div className="flex gap-4">
          <div className="flex-1 border border-slate-200 rounded-xl p-4 flex flex-col items-center text-center">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-7 h-7 rounded-full bg-blue-600 text-white flex items-center justify-center">
                <DollarSign size={14} />
              </div>
              <span className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Total Revenue</span>
            </div>
            <div className="text-xl font-black text-slate-900 mb-2">{summary.totalRevenue}</div>
            <div className="text-[11px] font-medium text-blue-600">Total Earnings</div>
          </div>
          <div className="flex-1 border border-slate-200 rounded-xl p-4 flex flex-col items-center text-center">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-7 h-7 rounded-full bg-emerald-500 text-white flex items-center justify-center">
                <TrendingUp size={14} />
              </div>
              <span className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Occupancy Rate</span>
            </div>
            <div className="text-xl font-black text-slate-900 mb-2">{summary.occupancyRate}%</div>
            <div className="text-[11px] font-medium text-emerald-600">&#8599; Avg Occupancy</div>
          </div>
          <div className="flex-1 border border-slate-200 rounded-xl p-4 flex flex-col items-center text-center">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-7 h-7 rounded-full bg-purple-500 text-white flex items-center justify-center">
                <CalendarCheck size={14} />
              </div>
              <span className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Total Bookings</span>
            </div>
            <div className="text-xl font-black text-slate-900 mb-2">{summary.totalBookings}</div>
            <div className="text-[11px] font-medium text-blue-600">New Bookings</div>
          </div>
          <div className="flex-1 border border-slate-200 rounded-xl p-4 flex flex-col items-center text-center">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-7 h-7 rounded-full bg-orange-500 text-white flex items-center justify-center">
                <Clock3 size={14} />
              </div>
              <span className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Avg Length of Stay</span>
            </div>
            <div className="text-xl font-black text-slate-900 mb-2">{summary.avgLOS} Nights</div>
            <div className="text-[11px] font-medium text-blue-600">Average Stay</div>
          </div>
          <div className="flex-1 border border-slate-200 rounded-xl p-4 flex flex-col items-center text-center">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-7 h-7 rounded-full bg-yellow-400 text-white flex items-center justify-center">
                <Star size={14} fill="currentColor" />
              </div>
              <span className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">Guest Satisfaction</span>
            </div>
            <div className="text-xl font-black text-slate-900 mb-2">{summary.guestSatisfaction} / 5</div>
            <div className="text-[11px] font-medium text-blue-600">Average Rating</div>
          </div>
        </div>
      </div>

      {/* Charts Section */}
      <div className="flex gap-4 h-[300px] mb-4">
        <div className="flex-1 border border-slate-200 rounded-xl p-5 flex flex-col">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-[11px] font-bold text-slate-800 uppercase tracking-wider">Revenue Trend</h3>
            <span className="text-[10px] text-slate-500 border border-slate-200 rounded px-2 py-1">Daily</span>
          </div>
          <div className="flex-1 -ml-4">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={revenueTrendData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#64748b" }} dy={10} />
                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#64748b" }} tickFormatter={(val) => \`Rs. \${val/1000}K\`} />
                <Line type="monotone" dataKey="revenue" stroke="#3b82f6" strokeWidth={2.5} dot={{ r: 3, fill: "#3b82f6", strokeWidth: 0 }} activeDot={{ r: 5 }} isAnimationActive={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="flex-1 border border-slate-200 rounded-xl p-5 flex flex-col">
          <div className="flex justify-between items-center mb-2">
            <h3 className="text-[11px] font-bold text-slate-800 uppercase tracking-wider">Occupancy Rate</h3>
          </div>
          <div className="flex-1 flex items-center justify-center gap-6">
            <div className="w-[140px] h-[140px] relative">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={occupancyData} innerRadius={50} outerRadius={70} paddingAngle={2} dataKey="value" stroke="none" isAnimationActive={false}>
                    {occupancyData.map((entry, index) => (
                      <Cell key={\`cell-\${index}\`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                </PieChart>
              </ResponsiveContainer>
              <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
                <span className="text-xl font-bold text-slate-900">{summary.occupancyRate}%</span>
                <span className="text-[10px] font-medium text-slate-500">Occupancy</span>
              </div>
            </div>
            <div className="flex flex-col gap-3">
              {occupancyData.map((entry, i) => (
                <div key={i} className="flex items-center gap-3">
                  <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: COLORS[i % COLORS.length] }}></div>
                  <span className="text-[11px] text-slate-600 font-medium w-20">{entry.name}</span>
                  <span className="text-[11px] font-bold text-slate-900">{entry.pct}%</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="flex-1 border border-slate-200 rounded-xl p-5 flex flex-col">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-[11px] font-bold text-slate-800 uppercase tracking-wider">Bookings Overview</h3>
            <span className="text-[10px] text-slate-500 border border-slate-200 rounded px-2 py-1">Daily</span>
          </div>
          <div className="flex-1 -ml-4">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={bookingsOverviewData} barSize={10}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#64748b" }} dy={10} />
                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: "#64748b" }} />
                <Bar dataKey="bookings" fill="#3b82f6" radius={[2, 2, 0, 0]} isAnimationActive={false} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
}
